[package]
name = "podstats"
version = "0.1.0"
authors = ["Andrew Michaud <dev@mail.andrewmichaud.com>"]

[dependencies]
rmp = "^0.8.6"
rmp-serde = "^0.13.1"
serde = "1.0.0"
serde_derive = "^1.0.2"
serde_yaml = "^0.7.0"
xdg = "^2.1.0"
